### ISSUE TITLE
Error: Not Found

### ISSUE THREAD

**Issue by jackwootton** [peter-evans/create-or-update-comment#116]
Having used this action for over a year, I'm now receiving `Error: Not Found`
```
peter-evans/create-or-update-comment@v2
```

**Comment by peter-evans** [comment]
Hi @jackwootton 

If you are using a PAT, check that it has not expired. Failed authentication often results in `Not Found` errors.

**Comment by jackwootton** [comment]
Thanks @peter-evans. I am using a GitHub secret to store a PAT which is used in the "Create or Update Comment" action. However, I didn't have any recently expired PATs. Nonetheless, I regenerated the PAT and updated the GitHub secret. The action is still failing with "Error: Not Found".

Is there anything else I can try?

**Comment by peter-evans** [comment]
`Not Found` is basically a 404 being returned from GitHub's APIs. So either it can't find the repo/issue/comment, or there is a permissions error causing the action to not have access to those resources.

Think about if you have made any changes that could cause this. The action hasn't changed, so it's unlikely to be something I can fix for you.

**Comment by jackwootton** [comment]
I'm sure you're right, but I'm not making much progress. I switched on debugging for the action

```
##[debug]RequestError [HttpError]: Not Found
##[debug]    at /home/runner/work/_actions/peter-evans/create-or-update-comment/v2.0.0/dist/index.js:3806:23
##[debug]    at processTicksAndRejections (node:internal/process/task_queues:96:5)
##[debug]    at async run (/home/runner/work/_actions/peter-evans/create-or-update-comment/v2.0.0/dist/index.js:8711:33) {
##[debug]  status: 404,
##[debug]  headers: {
##[debug]    'access-control-allow-origin': '*',
##[debug]    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
##[debug]    connection: 'close',
##[debug]    'content-encoding': 'gzip',
##[debug]    'content-security-policy': "default-src 'none'",
##[debug]    'content-type': 'application/json; charset=utf-8',
##[debug]    date: 'Fri, 17 Jun 2022 19:51:46 GMT',
##[debug]    'github-authentication-token-expiration': '2022-09-14 23:15:42 UTC',
##[debug]    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
##[debug]    server: 'GitHub.com',
##[debug]    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
##[debug]    'transfer-encoding': 'chunked',
##[debug]    vary: 'Accept-Encoding, Accept, X-Requested-With',
##[debug]    'x-accepted-oauth-scopes': '',
##[debug]    'x-content-type-options': 'nosniff',
##[debug]    'x-frame-options': 'deny',
##[debug]    'x-github-media-type': 'github.v3; format=json',
##[debug]    'x-github-request-id': '0400:7C00:276676:4C821F:62ACDB52',
##[debug]    'x-oauth-scopes': 'repo, workflow',
##[debug]    'x-ratelimit-limit': '5000',
##[debug]    'x-ratelimit-remaining': '4999',
##[debug]    'x-ratelimit-reset': '1655499106',
##[debug]    'x-ratelimit-resource': 'core',
##[debug]    'x-ratelimit-used': '1',
##[debug]    'x-xss-protection': '0'
##[debug]  },
##[debug]  request: {
##[debug]    method: 'POST',
##[debug]    url: 'https://api.github.com/repos/jsonsystems/api/issues/582/comments',
##[debug]    headers: {
##[debug]      accept: 'application/vnd.github.v3+json',
##[debug]      'user-agent': 'octokit-core.js/3.4.0 Node.js/16.13.0 (linux; x64)',
##[debug]      authorization: 'token [REDACTED]',
##[debug]      'content-type': 'application/json; charset=utf-8'
##[debug]    },
##[debug]    body: '{}',
##[debug]    request: { agent: [Agent], hook: [Function: bound bound register] }
##[debug]  },
##[debug]  documentation_url: 'https://docs.github.com/rest/reference/issues#create-an-issue-comment'
##[debug]}
```
